apiVersion: apps/v1
kind: Deployment
metadata:
  name: &service-name aprobado
  labels: &labels
    app: *service-name
spec:
  minReadySeconds: 1
  selector:
    matchLabels: *labels
  replicas: 1
  revisionHistoryLimit: 10
  template: 
    metadata:
      labels: *labels
    spec:
      containers:
      - name: *service-name
        image: vidanvgracias/aprobado:v1
        command: ["./binary"]
          